language: python
dist: xenial
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"
matrix:
    allow_failure:
        - "3.8-dev"
        - "nightly"
install:
    - pip install -e .[dev]
    - pip install codecov
script:
    - pytest -v --cov=src/ --cov-report=term tests
after_success:
    - codecov
notifications:
    on_success: change
    on_failure: always

