language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
matrix:
  allow_failures:
    - python: nightly
install:
  - pip install -e .[dev]
  - pip install codecov
script:
  - pytest -v --cov-report=term
after_success:
  - codecov
notifications:
  email:
    on_success: change
    on_failure: always
